"""
Enumerations for the Identity / Organisation / Multi-Tenant module.

Reference: ASAVEXA Master Blueprint, "Role & Permission Skill" and
"Segregation-of-Duties Skill".
"""
from enum import Enum


class Role(str, Enum):
    OWNER = "OWNER"
    ADMINISTRATOR = "ADMINISTRATOR"
    ACCOUNTANT = "ACCOUNTANT"
    FINANCE_OFFICER = "FINANCE_OFFICER"
    AUDITOR = "AUDITOR"
    REVIEWER = "REVIEWER"
    APPROVER = "APPROVER"
    MANAGER = "MANAGER"
    EXTERNAL_AUDITOR = "EXTERNAL_AUDITOR"
    INVESTOR_REVIEWER = "INVESTOR_REVIEWER"
    DONOR = "DONOR"
    REGULATOR = "REGULATOR"
    READ_ONLY = "READ_ONLY"


class MembershipStatus(str, Enum):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    REVOKED = "REVOKED"


class AuditAction(str, Enum):
    ORGANISATION_CREATED = "ORGANISATION_CREATED"
    USER_REGISTERED = "USER_REGISTERED"
    LOGIN_SUCCEEDED = "LOGIN_SUCCEEDED"
    LOGIN_FAILED = "LOGIN_FAILED"
    LOGOUT = "LOGOUT"
    ORG_CONTEXT_SELECTED = "ORG_CONTEXT_SELECTED"
    MEMBERSHIP_CREATED = "MEMBERSHIP_CREATED"
    MEMBERSHIP_ROLE_CHANGED = "MEMBERSHIP_ROLE_CHANGED"
    MEMBERSHIP_REVOKED = "MEMBERSHIP_REVOKED"
