"""Storage-agnostic repository contract for the one thing Period Close
persists: PeriodCloseProcess."""
from __future__ import annotations

from typing import List, Optional, Protocol

from ..domain.models import PeriodCloseProcess


class PeriodCloseRepository(Protocol):
    def create(self, process: PeriodCloseProcess) -> PeriodCloseProcess: ...
    def get(self, org_id: str, process_id: str) -> Optional[PeriodCloseProcess]: ...
    def update(self, process: PeriodCloseProcess) -> PeriodCloseProcess: ...
    def list_for_period(self, org_id: str, period_id: str) -> List[PeriodCloseProcess]: ...
    def get_active_for_period(self, org_id: str, period_id: str) -> Optional[PeriodCloseProcess]: ...
