"""Storage-agnostic repository contracts for Reconciliation. Same
pattern as every other module: the service layer depends only on these
Protocols, never on SQLite or SQLAlchemy directly."""
from __future__ import annotations

from typing import List, Optional, Protocol

from ..domain.models import BankTransaction, Reconciliation


class ReconciliationRepository(Protocol):
    def create(self, reconciliation: Reconciliation) -> Reconciliation: ...
    def get(self, org_id: str, reconciliation_id: str) -> Optional[Reconciliation]: ...
    def update(self, reconciliation: Reconciliation) -> Reconciliation: ...
    def list_for_org(
        self, org_id: str, bank_account_id: Optional[str] = None, status: Optional[str] = None
    ) -> List[Reconciliation]: ...


class BankTransactionRepository(Protocol):
    def create(self, transaction: BankTransaction) -> BankTransaction: ...
    def get(self, org_id: str, transaction_id: str) -> Optional[BankTransaction]: ...
    def update(self, transaction: BankTransaction) -> BankTransaction: ...
    def list_for_reconciliation(self, org_id: str, reconciliation_id: str) -> List[BankTransaction]: ...
    def list_for_account(self, org_id: str, bank_account_id: str) -> List[BankTransaction]: ...
    def get_by_dedup_hash(self, org_id: str, bank_account_id: str, dedup_hash: str) -> Optional[BankTransaction]: ...
