"""
Repository interfaces for the Identity / Organisation / Multi-Tenant
module. Same pattern as accounting/repository/interfaces.py: the
service layer depends only on these Protocols, never on SQLite or
SQLAlchemy directly.
"""
from __future__ import annotations

from typing import List, Optional, Protocol

from ..domain.models import Membership, Organisation, Session, User


class OrganisationRepository(Protocol):
    def create(self, org: Organisation) -> Organisation: ...
    def get(self, org_id: str) -> Optional[Organisation]: ...
    def list_all(self) -> List[Organisation]: ...


class UserRepository(Protocol):
    def create(self, user: User) -> User: ...
    def get(self, user_id: str) -> Optional[User]: ...
    def get_by_email(self, email: str) -> Optional[User]: ...
    def update(self, user: User) -> User: ...


class MembershipRepository(Protocol):
    def create(self, membership: Membership) -> Membership: ...
    def get(self, org_id: str, user_id: str) -> Optional[Membership]: ...
    def update(self, membership: Membership) -> Membership: ...
    def list_for_org(self, org_id: str) -> List[Membership]: ...
    def list_for_user(self, user_id: str) -> List[Membership]: ...


class SessionRepository(Protocol):
    def create(self, session: Session) -> Session: ...
    def get_by_token_hash(self, token_hash: str) -> Optional[Session]: ...
    def update(self, session: Session) -> Session: ...
