"""Storage-agnostic repository contracts for Controls & Compliance.
Same pattern as every other module: the service layer depends only on
these Protocols, never on SQLite or SQLAlchemy directly."""
from __future__ import annotations

from typing import List, Optional, Protocol

from ..domain.models import ControlDefinition, ControlExecution, Finding, Remediation


class ControlDefinitionRepository(Protocol):
    def create(self, definition: ControlDefinition) -> ControlDefinition: ...
    def get(self, org_id: str, definition_id: str) -> Optional[ControlDefinition]: ...
    def get_by_code(self, org_id: str, code: str) -> Optional[ControlDefinition]: ...
    def update(self, definition: ControlDefinition) -> ControlDefinition: ...
    def list_for_org(self, org_id: str, active_only: bool = False) -> List[ControlDefinition]: ...


class ControlExecutionRepository(Protocol):
    def create(self, execution: ControlExecution) -> ControlExecution: ...
    def get(self, org_id: str, execution_id: str) -> Optional[ControlExecution]: ...
    def update(self, execution: ControlExecution) -> ControlExecution: ...
    def list_for_control(self, org_id: str, control_id: str) -> List[ControlExecution]: ...
    def list_for_org(self, org_id: str, period_id: Optional[str] = None) -> List[ControlExecution]: ...


class FindingRepository(Protocol):
    def create(self, finding: Finding) -> Finding: ...
    def get(self, org_id: str, finding_id: str) -> Optional[Finding]: ...
    def update(self, finding: Finding) -> Finding: ...
    def list_for_org(self, org_id: str, status: Optional[str] = None) -> List[Finding]: ...
    def list_for_control(self, org_id: str, control_id: str) -> List[Finding]: ...


class RemediationRepository(Protocol):
    def create(self, remediation: Remediation) -> Remediation: ...
    def get(self, org_id: str, remediation_id: str) -> Optional[Remediation]: ...
    def update(self, remediation: Remediation) -> Remediation: ...
    def list_for_finding(self, org_id: str, finding_id: str) -> List[Remediation]: ...
