"""Storage-agnostic repository contract for the Evidence Vault."""
from __future__ import annotations

from typing import List, Optional, Protocol

from ..domain.models import EvidenceRecord


class EvidenceRepository(Protocol):
    def create(self, record: EvidenceRecord) -> EvidenceRecord: ...
    def get(self, org_id: str, evidence_id: str) -> Optional[EvidenceRecord]: ...
    def get_by_hash(self, org_id: str, file_hash: str) -> Optional[EvidenceRecord]: ...
    def update(self, record: EvidenceRecord) -> EvidenceRecord: ...
    def list_for_org(self, org_id: str) -> List[EvidenceRecord]: ...
    def find_for_journal(self, org_id: str, journal_id: str) -> Optional[EvidenceRecord]: ...
    def find_for_transaction_ref(self, org_id: str, transaction_ref: str) -> Optional[EvidenceRecord]: ...
