/**
 * Permission constants and role matrix — mirrored exactly from the
 * backend's canonical registry at
 * src/asavexa/identity/domain/permissions.py. Nothing here is
 * invented; every constant and every role's grant set was copied from
 * that file, not guessed from the UI's needs.
 *
 * IMPORTANT: this is a UX convenience only. Per the backend's own
 * architecture (see docs/security-architecture.md), authorization is
 * enforced exclusively by the API — this module lets the UI decide
 * what to *show*, never what to *allow*. Every mutating action still
 * goes through the real API call, which the backend can and will
 * reject independently of what this module says. See
 * docs/frontend-runtime-verification.md, "Permission-aware UI is UX,
 * not security."
 */

export const PERMISSIONS = Object.freeze({
  ORG_MANAGE_USERS: "org:manage_users",
  ORG_MANAGE_SETTINGS: "org:manage_settings",
  ACCOUNT_MANAGE: "account:manage",
  PERIOD_MANAGE: "period:manage",
  JOURNAL_CREATE: "journal:create",
  JOURNAL_POST: "journal:post",
  JOURNAL_REVERSE: "journal:reverse",
  LEDGER_READ: "ledger:read",
  EVIDENCE_UPLOAD: "evidence:upload",
  EVIDENCE_VERIFY: "evidence:verify",
  EVIDENCE_READ: "evidence:read",
  RECONCILIATION_IMPORT: "reconciliation:import",
  RECONCILIATION_CREATE: "reconciliation:create",
  RECONCILIATION_MATCH: "reconciliation:match",
  RECONCILIATION_APPROVE: "reconciliation:approve",
  RECONCILIATION_READ: "reconciliation:read",
  REPORTING_READ: "reporting:read",
  PERIOD_CLOSE_REQUEST: "period_close:request",
  PERIOD_CLOSE_REVIEW: "period_close:review",
  PERIOD_CLOSE_APPROVE: "period_close:approve",
  PERIOD_CLOSE_READ: "period_close:read",
  CONTROL_READ: "control:read",
  CONTROL_MANAGE: "control:manage",
  CONTROL_EXECUTE: "control:execute",
  FINDING_MANAGE: "finding:manage",
  FINDING_REMEDIATE: "finding:remediate",
  FINDING_VERIFY: "finding:verify",
  AUDIT_READ: "audit:read",
  PASSPORT_MANAGE: "passport:manage",
  SECURITY_MANAGE: "security:manage",
});

/** Every permission string, for the one role (OWNER) that holds them all. */
const ALL_PERMISSIONS = Object.values(PERMISSIONS);

/**
 * Role -> granted permission strings. Copied field-for-field from
 * ROLE_PERMISSIONS in the backend. If the backend's matrix changes,
 * this must be updated to match — there is deliberately no attempt to
 * "derive" it cleverly, since the backend is the single source of
 * truth and a divergent copy here would be worse than an honest,
 * flat mirror.
 */
export const ROLE_PERMISSIONS = Object.freeze({
  OWNER: ALL_PERMISSIONS,
  ADMINISTRATOR: [
    PERMISSIONS.ORG_MANAGE_USERS, PERMISSIONS.ORG_MANAGE_SETTINGS,
    PERMISSIONS.ACCOUNT_MANAGE, PERMISSIONS.PERIOD_MANAGE,
    PERMISSIONS.LEDGER_READ, PERMISSIONS.EVIDENCE_READ, PERMISSIONS.RECONCILIATION_READ,
    PERMISSIONS.REPORTING_READ, PERMISSIONS.PERIOD_CLOSE_READ,
    PERMISSIONS.CONTROL_READ, PERMISSIONS.CONTROL_MANAGE, PERMISSIONS.FINDING_MANAGE,
    PERMISSIONS.AUDIT_READ, PERMISSIONS.PASSPORT_MANAGE, PERMISSIONS.SECURITY_MANAGE,
  ],
  ACCOUNTANT: [
    PERMISSIONS.JOURNAL_CREATE, PERMISSIONS.LEDGER_READ,
    PERMISSIONS.EVIDENCE_UPLOAD, PERMISSIONS.EVIDENCE_READ,
    PERMISSIONS.RECONCILIATION_IMPORT, PERMISSIONS.RECONCILIATION_CREATE,
    PERMISSIONS.RECONCILIATION_MATCH, PERMISSIONS.RECONCILIATION_READ,
    PERMISSIONS.REPORTING_READ, PERMISSIONS.PERIOD_CLOSE_REQUEST, PERMISSIONS.PERIOD_CLOSE_READ,
    PERMISSIONS.CONTROL_READ, PERMISSIONS.CONTROL_EXECUTE, PERMISSIONS.FINDING_REMEDIATE,
  ],
  FINANCE_OFFICER: [
    PERMISSIONS.PERIOD_MANAGE, PERMISSIONS.JOURNAL_CREATE, PERMISSIONS.JOURNAL_POST,
    PERMISSIONS.JOURNAL_REVERSE, PERMISSIONS.LEDGER_READ,
    PERMISSIONS.EVIDENCE_UPLOAD, PERMISSIONS.EVIDENCE_VERIFY, PERMISSIONS.EVIDENCE_READ,
    PERMISSIONS.RECONCILIATION_IMPORT, PERMISSIONS.RECONCILIATION_CREATE,
    PERMISSIONS.RECONCILIATION_MATCH, PERMISSIONS.RECONCILIATION_APPROVE, PERMISSIONS.RECONCILIATION_READ,
    PERMISSIONS.REPORTING_READ,
    PERMISSIONS.PERIOD_CLOSE_REQUEST, PERMISSIONS.PERIOD_CLOSE_REVIEW,
    PERMISSIONS.PERIOD_CLOSE_APPROVE, PERMISSIONS.PERIOD_CLOSE_READ,
    PERMISSIONS.CONTROL_READ, PERMISSIONS.CONTROL_MANAGE, PERMISSIONS.CONTROL_EXECUTE,
    PERMISSIONS.FINDING_MANAGE, PERMISSIONS.FINDING_REMEDIATE, PERMISSIONS.FINDING_VERIFY,
  ],
  APPROVER: [
    PERMISSIONS.JOURNAL_POST, PERMISSIONS.JOURNAL_REVERSE, PERMISSIONS.LEDGER_READ,
    PERMISSIONS.EVIDENCE_VERIFY, PERMISSIONS.EVIDENCE_READ, PERMISSIONS.AUDIT_READ,
    PERMISSIONS.RECONCILIATION_APPROVE, PERMISSIONS.RECONCILIATION_READ, PERMISSIONS.REPORTING_READ,
    PERMISSIONS.PERIOD_CLOSE_REVIEW, PERMISSIONS.PERIOD_CLOSE_APPROVE, PERMISSIONS.PERIOD_CLOSE_READ,
    PERMISSIONS.CONTROL_READ, PERMISSIONS.CONTROL_EXECUTE, PERMISSIONS.FINDING_VERIFY,
  ],
  REVIEWER: [
    PERMISSIONS.LEDGER_READ, PERMISSIONS.EVIDENCE_READ, PERMISSIONS.RECONCILIATION_READ,
    PERMISSIONS.REPORTING_READ, PERMISSIONS.PERIOD_CLOSE_READ, PERMISSIONS.CONTROL_READ, PERMISSIONS.AUDIT_READ,
  ],
  MANAGER: [
    PERMISSIONS.LEDGER_READ, PERMISSIONS.EVIDENCE_READ, PERMISSIONS.RECONCILIATION_READ,
    PERMISSIONS.REPORTING_READ, PERMISSIONS.PERIOD_CLOSE_READ, PERMISSIONS.CONTROL_READ,
    PERMISSIONS.AUDIT_READ, PERMISSIONS.PASSPORT_MANAGE,
  ],
  AUDITOR: [
    PERMISSIONS.LEDGER_READ, PERMISSIONS.EVIDENCE_READ, PERMISSIONS.RECONCILIATION_READ,
    PERMISSIONS.REPORTING_READ, PERMISSIONS.PERIOD_CLOSE_READ, PERMISSIONS.CONTROL_READ, PERMISSIONS.AUDIT_READ,
  ],
  EXTERNAL_AUDITOR: [
    PERMISSIONS.LEDGER_READ, PERMISSIONS.EVIDENCE_READ, PERMISSIONS.RECONCILIATION_READ,
    PERMISSIONS.REPORTING_READ, PERMISSIONS.PERIOD_CLOSE_READ, PERMISSIONS.CONTROL_READ, PERMISSIONS.AUDIT_READ,
  ],
  READ_ONLY: [
    PERMISSIONS.LEDGER_READ, PERMISSIONS.EVIDENCE_READ, PERMISSIONS.RECONCILIATION_READ,
    PERMISSIONS.REPORTING_READ, PERMISSIONS.PERIOD_CLOSE_READ, PERMISSIONS.CONTROL_READ, PERMISSIONS.AUDIT_READ,
  ],
  INVESTOR_REVIEWER: [],
  DONOR: [],
  REGULATOR: [],
});

/**
 * can(role, permission) — the frontend's single permission-check
 * entry point. UX only; see module docstring.
 */
export function can(role, permission) {
  if (!role || !permission) return false;
  const granted = ROLE_PERMISSIONS[role];
  return Array.isArray(granted) && granted.includes(permission);
}
